In [6]:
# Salary Prediction Phase1 using SLR Model Creation.
#Pandas Pandas is a Python library used to store, organize, clean, analyze, and manipulate data easily, similar to working with Excel spreadsheets.
import pandas as pd #(pandas = pd)

In [9]:
dataset=pd.read_csv("Salary_Data.csv") #Calling source csv file and should place the csv file in the same path where you have this place.

In [11]:
dataset #Execute the csv file to view the dataset.

    years_of_experience  monthly_salary_inr
0                     0               18000
1                     1               22000
2                     2               26000
3                     3               30000
4                     4               34000
5                     5               39000
6                     6               43000
7                     7               48000
8                     8               52000
9                     9               58000
10                   10               63000
11                   11               68000
12                   12               74000
13                   13               79000
14                   14               85000
15                   15               92000
16                   16               98000
17                   18              110000
18                   20              125000

In [30]:
independent=dataset[["years_of_experience"]] #Invoke the input column values and assiging to the variable named as independent x  input
independent

    years_of_experience
0                     0
1                     1
2                     2
3                     3
4                     4
5                     5
6                     6
7                     7
8                     8
9                     9
10                   10
11                   11
12                   12
13                   13
14                   14
15                   15
16                   16
17                   18
18                   20

In [31]:
dependent= dataset ["monthly_salary_inr"] #Invoke the input column values and assiging to the variable named as dependent y output
dependent

0      18000
1      22000
2      26000
3      30000
4      34000
5      39000
6      43000
7      48000
8      52000
9      58000
10     63000
11     68000
12     74000
13     79000
14     85000
15     92000
16     98000
17    110000
18    125000
Name: monthly_salary_inr, dtype: int64

In [32]:
#Split Training Set and Test Set.
from sklearn.model_selection import train_test_split #Scikit-learn, a Python Machine Learning library, ,model_selection - A module used to select and evaluate ML models, train_test_split - A function used to split data into training and testing datasets  
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30, random_state=0) #x_train (input training),x_test (input testing),y_train(output training), y_test (output testing)

In [33]:
from sklearn.linear_model import LinearRegression #used to import the Linear Regression algorithm from the Scikit-le0arn library
regressor = LinearRegression() # model creation - linearregression considered as a class assigned to the variable regressor.
regressor.fit(x_train,y_train) #Train the Linear Regression model using the training input data and its corresponding actual output values.

LinearRegression()

In [35]:
# Extract the weight (slope/coefficient) learned by the Linear Regression model.
# It represents how much the predicted output (Salary) changes when the input
# feature (Experience) increases by 1 unit.
weight=regressor.coef_
weight

array([5084.74208929])

In [37]:
# It is the predicted Salary when Experience is 0
bais=regressor.intercept_
bais

np.float64(14238.621586475943)

In [38]:
# Use the trained model to predict Salary for the test input data
# x_test contains the Experience values that the model has not used for training
y_pred=regressor.predict(x_test)

In [47]:
# Import the R² score evaluation function from sklearn
from sklearn.metrics import r2_score

# Compare actual Salary values (y_test) with predicted Salary values (y_pred)
# R² indicates how well the model explains the variation in the actual values
r2_score=r2_score(y_test,y_pred)

# Display the R² score
r2_score

0.9836243118351113

In [48]:
# Import the pickle library.
# Pickle is used to save Python objects into a file and load them later.
import pickle 
# Specify the name of the file where the trained model will be saved.
# The .sav extension is commonly used for saved model files.
filename="finalized_model_linear.sav"

In [49]:
# Save the trained Linear Regression model into the specified file.
# regressor  = the trained model
# open()     = opens the file
# filename   = name of the file
# 'wb'       = write in binary mode
# pickle.dump() = converts and writes the model object into the file
pickle.dump(regressor,open(filename,'wb'))

In [54]:
# Validate whether the saved model can be loaded and used for prediction.
# If successful, we can proceed to the next phase of deployment.
# Open the saved model file in read-binary ('rb') mode and load it.
# pickle.load() reads the saved model and restores it as a Python object.
loaded_model = pickle.load(open("finalized_model_linear.sav",'rb'))
# Use the loaded model to predict the output for a new input.
# Here, 30 represents 30 years of Experience.
# Double square brackets are used because the model expects 2D input data.
result=loaded_model.predict([[12]])
# Display the predicted result
result

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([75255.526658])